version: '3.3'

services:
   nginx:
     depends_on: 
       - wordpress
     image: nginx:1.14.2-alpine
     restart: always
     ports:
       - 80:80
       - 443:443
     volumes_from:
       - wordpress
     volumes:
       - db_data:/etc/nginx/
     networks: 
       - wp-network
   wordpress:
     depends_on:
       - db
     image: wordpress:5.1.0-php7.1-fpm-alpine
     volumes:
       - wordpress_files:/var/www/html
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: my_wordpress_db_password
     networks: 
       - wp-network

   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: my_db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: my_wordpress_db_password
networks:
    wp-network:
       driver: bridge

volumes:
    wordpress_files:
    db_data: